main:
  - name: INTRODUCTION
    identifier: introduction
    url: /introduction/
    weight: 10

  - name: About Laboratory
    parent: introduction
    url: /introduction/#about
    weight: 11

  - name: Research Areas
    parent: introduction
    url: /introduction/#research-areas
    weight: 12

  - name: Capabilities
    parent: introduction
    url: /introduction/#equipment
    weight: 13

  - name: Contact
    parent: introduction
    url: /introduction/#contact
    weight: 14

  - name: MEMBERS
    identifier: members
    url: /members/
    weight: 20

  - name: Professor
    parent: members
    url: /members/#professor
    weight: 21

  - name: Students
    parent: members
    url: /members/#graduate-students
    weight: 22

  - name: RESEARCH
    identifier: research
    url: /research/
    weight: 30

  - name: PUBLICATIONS
    identifier: publications
    url: /publications/
    weight: 40

  - name: BOARD
    identifier: board
    url: /board/
    weight: 50

  - name: Notice
    parent: board
    url: /board/#notice
    weight: 51

  - name: News
    parent: board
    url: /board/#news
    weight: 52

  - name: Gallery
    parent: board
    url: /board/#gallery
    weight: 53
