main:
  - name: INTRODUCTION
    identifier: introduction
    url: /introduction/
    weight: 10

  - name: About Lab
    parent: introduction
    url: /introduction/#about
    weight: 11

  - name: Equipment
    parent: introduction
    url: /introduction/#equipment
    weight: 12

  - name: Contact
    parent: introduction
    url: /introduction/#contact
    weight: 13

  - name: PROFESSOR
    url: /professor/
    weight: 20

  - name: MEMBERS
    identifier: members
    url: /members/
    weight: 30

  - name: PUBLICATIONS
    url: /#publications
    weight: 40

  - name: RESEARCH
    identifier: research
    url: /research/
    weight: 50

  - name: BOARD
    url: /#board
    weight: 60
