main:
  - name: INTRODUCTION
    url: /#introduction
    weight: 10

  - name: PROFESSOR
    url: /#professor
    weight: 20

  - name: MEMBERS
    url: /#members
    weight: 30

  - name: PUBLICATIONS
    url: /#publications
    weight: 40

  - name: RESEARCH
    url: /#research
    weight: 50

  - name: BOARD
    url: /#board
    weight: 60
